version: "3"
services:
  go:
    image: golang:latest
    container_name: main
    volumes:
      - ./main:/go
    tty: true
  web:
    image: nginx:alpine
    ports:
      - 8888:80
    privileged: true
    volumes:
      - "./sampleapp/views:/usr/share/nginx/html"
      - "./sampleapp/assets:/usr/share/nginx/assets"